pool:
  name: Default
steps:
- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: backend
    repository: 'lexitas backend'
    Dockerfile: ShopAdminTool.Server/Dockerfile
    tags: |
     $(Build.BuildId)
     latest
steps:
- task: AzureWebAppContainer@1
  displayName: 'Azure Web App on Container Deploy: dotnetbackend007'
  inputs:
    azureSubscription: 'Free Trial (d25c3f37-60f9-4b6d-bb35-df401fa85d76)'
    appName: dotnetbackend007
    containers: 'backendandfrontend.azurecr.io/lexitasbackend:latest'
