trigger: 
  branches:
    include:
      - develop
 
pool:
  vmImage: windows-latest
 
variables:
- name: buildConfiguration
  value: 'Release'
 
stages:
  - stage: build
    displayName: 'Build Rasi Business lincensing Backend Dev'
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
    jobs: 
      - job: RCBBuild
        steps:
 
        - task: UseDotNet@2
          displayName: 'Install .NET Core SDK'
          inputs:
            version: 8.x #Changed 7.x to 8.x
        
        - task: NuGetToolInstaller@1
          inputs:
            versionSpec: 
            checkLatest: true
 
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: '**/*.csproj'
 
        - task: DotNetCoreCLI@2
          displayName: 'Build Rasi Business lincensing Backend Solution'
          inputs:
            command: 'build'
            projects: '**/*.sln'
            arguments: '--no-restore'
 
        - task: DotNetCoreCLI@2
          displayName: 'Prepare Business lincensing Backend API application publish'
          inputs:
            command: 'publish'
            publishWebProjects: true
            arguments: '--no-restore'
 
 
        - task: AzureWebApp@1
          displayName: 'Deploy Business lincensing Backend Dev'
          inputs:
            azureSubscription: 'github.com_arjun0201'
            appType: 'webApp'
            appName: 'RASI-DEV-BL-AS'
            package: '$(System.DefaultWorkingDirectory)/**/*.zip'
            deploymentMethod: 'auto'
