version: '1'
services:
  
  # .NET CONTAINER
  api:
    container_name: api
    ports:
      - 7103:7103
      - 5248:5248
    build:
      context: ./ShopAdminTool.Server
      dockerfile: Dockerfile
    networks:
      - shopadmin
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      ASPNETCORE_HTTPS_PORT: 7103
      ASPNETCORE_URLS: "https://+:7103;http://+:5248"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "password"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/usr/local/share/ca-certificates/localhost.pfx"
      DatabaseSettings__ConnectionString: "Server=mssql;Database=ShopAdminToolDatabase;User=sa;Password=Pa$$$$word123!;MultipleActiveResultSets=true;Encrypt=false"
      DatabaseSettings__DbProvider: "mssql"
    
  # React container
  client:
    stdin_open: true
    container_name: client
    build:
      context: "./shop-admin-tool.web"
      dockerfile: Dockerfile
    volumes:
      - "./shop-admin-tool.web:/app"
      - "/app/node_modules"
    depends_on:
      - api
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"

  # Sql Server 
  mssql:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "Pa$$$$word123!"
      ACCEPT_EULA: Y
    container_name: mssql
    volumes:
      - mssql-data:/data/db
    ports:
      - 1533:1433
    networks:
      - shopadmin
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q
        "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
volumes:
  mssql-data:
networks:
  shopadmin:
    name:  shopadmin
